# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'MyTouTiao' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire' #类仿afn
  pod 'SwiftyJSON' #json转model
  pod 'SwiftTheme'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'FDFullscreenPopGesture'
  pod 'SGPagingView'
  pod 'HandyJSON'
  pod 'SQLite.swift'
end
