# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'MyTouTiao' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire' #类仿afn
  pod 'SwiftyJSON' #json转model
  pod 'SwiftTheme' #app样式
  pod 'SVProgressHUD' #吐丝
  pod 'MJRefresh' #下拉刷新
  pod 'FDFullscreenPopGesture' #手势
  pod 'SGPagingView' #滑动的标题
  pod 'HandyJSON' #json转model
  pod 'SQLite.swift' #数据库
  pod 'RxCocoa' #函数响应式编程
  pod 'RxSwift' #函数响应式编程
  pod 'IBAnimatable' #转场动化
  pod 'Kingfisher' #图片处理
  pod 'BMPlayer'  #音视频效果
  pod 'lottie-ios' #动画特效
end
